server:
  port: 80
kafka:
  bootstrap-servers: localhost:9092
spring:
  influxdb:
    url: http://localhost:8086
    username: admin
    password: admin
    database: GoProxy
    retention-policy: autogen
    gzip: true